const fs = require('fs');

const generateQuestions = () => {
  const q = [];
  
  // Helper to add questions quickly
  const add = (question, options, correctAnswer, explanation, topic, difficulty) => {
    q.push({ id: q.length + 1, question, options, correctAnswer, explanation, topic, difficulty });
  };

  // --- 40 EASY QUESTIONS ---
  add("What is React?", ["A relational database", "A JavaScript library for building user interfaces", "A CSS framework", "A backend server"], "A JavaScript library for building user interfaces", "React is a JS library used to build UIs.", "React Introduction", "Easy");
  add("Who maintains React?", ["Google", "Facebook (Meta)", "Microsoft", "Twitter"], "Facebook (Meta)", "React was created and is maintained by Facebook/Meta.", "React Introduction", "Easy");
  add("What command is used to create a React application using create-react-app?", ["npx create-react-app my-app", "npm install react-app", "npm build react-app", "npx new-react my-app"], "npx create-react-app my-app", "The standard tool is create-react-app.", "React Get Started", "Easy");
  add("Which method is used to render a React element into the DOM in React 18?", ["ReactDOM.render()", "React.mount()", "ReactDOM.createRoot().render()", "document.render()"], "ReactDOM.createRoot().render()", "In React 18, createRoot is used.", "React Render HTML", "Easy");
  add("What is JSX?", ["JavaScript XML", "Java Syntax Extension", "JSON XML", "JavaScript X-Mode"], "JavaScript XML", "JSX stands for JavaScript XML.", "JSX Intro", "Easy");
  add("How do you write a comment in JSX?", ["// comment", "<!-- comment -->", "{/* comment */}", "/* comment */"], "{/* comment */}", "JSX comments must be wrapped in braces.", "JSX Intro", "Easy");
  add("Which HTML attribute is written as 'className' in JSX?", ["class", "id", "style", "name"], "class", "Because class is a reserved word in JS.", "JSX Attributes", "Easy");
  add("What is the correct way to specify an inline style in React?", ["style=\"color: red\"", "style={{color: 'red'}}", "style={color: 'red'}", "class=\"color-red\""], "style={{color: 'red'}}", "Inline styles are passed as objects in React.", "React CSS Styling", "Easy");
  add("A functional component must return how many root DOM nodes?", ["One", "Two", "Three", "Any number"], "One", "React components must return a single root element.", "Function Components", "Easy");
  add("What are Props in React?", ["Functions", "Methods", "Arguments passed into React components", "State variables"], "Arguments passed into React components", "Props are like function arguments.", "React Props", "Easy");
  add("Props are passed to components via...", ["HTML attributes", "State", "Context", "Variables"], "HTML attributes", "Props are passed like HTML attributes.", "React Props", "Easy");
  add("Can props be modified by the receiving component?", ["Yes", "No", "Only if it's a class component", "Only if it's a function component"], "No", "Props are read-only.", "React Props", "Easy");
  add("What is a Class Component in React?", ["A simple JS function", "A class extending React.Component", "A variable", "A Hook"], "A class extending React.Component", "Class components must extend React.Component.", "Class Components", "Easy");
  add("How do you handle events in React?", ["onclick", "onClick", "on-click", "clickEvent"], "onClick", "React events use camelCase.", "React Events", "Easy");
  add("Which method is commonly used to loop over arrays in React JSX?", ["forEach()", "map()", "filter()", "reduce()"], "map()", "map() is used to render lists.", "ES6 Array map()", "Easy");
  add("What must each element in a React list have?", ["An id", "A ref", "A unique 'key' prop", "A class"], "A unique 'key' prop", "Keys help React identify changed items.", "Keys", "Easy");
  add("What is React State?", ["An object storing component data", "A global variable", "A CSS file", "A DOM element"], "An object storing component data", "State is an object holding data that can change over time.", "Components", "Easy");
  add("Which Hook is used to add state to a function component?", ["useState", "useEffect", "useContext", "useRef"], "useState", "useState is the Hook for state.", "useState", "Easy");
  add("What does useState return?", ["A value and a function", "An array with two elements", "An object", "A single value"], "An array with two elements", "It returns the state variable and a setter function.", "useState", "Easy");
  add("What Hook is used for side effects in React?", ["useState", "useEffect", "useContext", "useRef"], "useEffect", "useEffect runs side effects.", "useEffect", "Easy");
  add("What does the 'let' keyword do in ES6?", ["Declares a global variable", "Declares a block-scoped variable", "Defines a constant", "Creates a class"], "Declares a block-scoped variable", "let allows block-scoped variable declaration.", "ES6 Variables", "Easy");
  add("Which ES6 feature is used to extract values from arrays or objects into distinct variables?", ["Spread operator", "Destructuring", "Arrow functions", "Modules"], "Destructuring", "Destructuring unpacks values.", "ES6 Destructuring", "Easy");
  add("What symbol is used for the spread operator in ES6?", ["...", "&&", "||", "=>"], "...", "Three dots are used for spread.", "ES6 Spread Operator", "Easy");
  add("How do you write a ternary operator?", ["condition ? true : false", "condition ! true : false", "condition & true : false", "condition || true : false"], "condition ? true : false", "Ternary uses the ? and : syntax.", "ES6 Ternary Operator", "Easy");
  add("Which syntax imports a module in ES6?", ["require('module')", "include 'module'", "import module from 'module'", "fetch('module')"], "import module from 'module'", "ES6 uses the import statement.", "ES6 Modules", "Easy");
  add("React is mainly used to build:", ["Single-page applications (SPAs)", "Databases", "Operating Systems", "Hardware"], "Single-page applications (SPAs)", "React builds fast SPAs.", "React Introduction", "Easy");
  add("How do you embed JavaScript expressions in JSX?", ["Using quotes \" \"", "Using curly braces { }", "Using brackets [ ]", "Using parentheses ( )"], "Using curly braces { }", "Braces wrap JS expressions in JSX.", "JSX Expressions", "Easy");
  add("What is the correct way to write an arrow function?", ["function = () => {}", "() => {}", "=> {}", "function() => {}"], "() => {}", "Arrow functions use the () => syntax.", "ES6 Arrow Functions", "Easy");
  add("Which attribute is used to group multiple HTML tags in JSX without adding an extra node to the DOM?", ["<div>", "<group>", "<React.Fragment>", "<section>"], "<React.Fragment>", "Fragments group elements without adding a DOM node.", "JSX Intro", "Easy");
  add("How do you create a React component named 'Hello'?", ["function Hello() {}", "const Hello = () => {}", "Both function and arrow function", "class Hello() {}"], "Both function and arrow function", "Both syntax are valid for function components.", "Function Components", "Easy");
  add("How do you pass a prop named 'color' with value 'blue' to a component?", ["<Car color=\"blue\" />", "<Car {color: 'blue'} />", "<Car>color='blue'</Car>", "<Car props={color: 'blue'} />"], "<Car color=\"blue\" />", "Props are passed like HTML attributes.", "React Props", "Easy");
  add("To use a React Hook, you must import it from:", ["react-dom", "react", "react-hooks", "react-router"], "react", "Hooks are imported from the 'react' package.", "What is Hooks?", "Easy");
  add("Which Hook is used to reference a DOM element?", ["useRef", "useEffect", "useMemo", "useContext"], "useRef", "useRef provides a direct reference to a DOM element.", "useRef", "Easy");
  add("What is the primary purpose of Context in React?", ["To manage state locally", "To avoid passing props through intermediate components", "To fetch API data", "To route between pages"], "To avoid passing props through intermediate components", "Context provides a way to pass data without prop drilling.", "useContext", "Easy");
  add("What is React Router used for?", ["Styling components", "Routing requests in SPAs", "State management", "Server-side rendering"], "Routing requests in SPAs", "React Router enables navigation in a React app.", "React Router", "Easy");
  add("Which component from React Router wraps the entire application?", ["<Route>", "<Link>", "<BrowserRouter>", "<Switch>"], "<BrowserRouter>", "BrowserRouter is the parent component for routing.", "React Router", "Easy");
  add("How do you create a link using React Router?", ["<a href='/home'>", "<Link to='/home'>", "<Router href='/home'>", "<Nav to='/home'>"], "<Link to='/home'>", "React Router uses the Link component.", "React Router", "Easy");
  add("In React Forms, a form element whose value is controlled by React is called a:", ["Controlled component", "Uncontrolled component", "Stateful form", "Reactive form"], "Controlled component", "Controlled components have their state managed by React.", "React Forms", "Easy");
  add("To handle multiple inputs in a React form, you usually use:", ["Multiple state variables", "A single state object and event.target.name", "Refs for every input", "Context"], "A single state object and event.target.name", "Using event.target.name simplifies handling multiple inputs.", "Multiple Inputs", "Easy");
  add("Which Hook is used to manage complex state logic?", ["useState", "useEffect", "useReducer", "useRef"], "useReducer", "useReducer is preferred for complex state logic.", "useReducer", "Easy");

  // --- 35 INTERMEDIATE QUESTIONS ---
  add("What is the output of the map function in a list component?", ["A single HTML string", "An array of React elements", "A modified array", "A boolean"], "An array of React elements", "map() transforms data into an array of JSX elements.", "React Lists", "Intermediate");
  add("What happens if you don't provide a key to a list item?", ["The app crashes", "React throws a warning in the console", "The items don't render", "It automatically adds random keys"], "React throws a warning in the console", "Missing keys cause warnings and potential rendering bugs.", "Keys", "Intermediate");
  add("When updating an array in state, what is the best practice?", ["Modify the array directly", "Use array.push()", "Create a new copy of the array using spread operator", "Use delete keyword"], "Create a new copy of the array using spread operator", "State must be treated as immutable.", "useState", "Intermediate");
  add("How do you run useEffect only once after the initial render?", ["Pass no dependency array", "Pass an empty array []", "Return false", "Pass [true]"], "Pass an empty array []", "An empty dependency array means it runs only on mount.", "useEffect", "Intermediate");
  add("What is the purpose of the cleanup function in useEffect?", ["To clear the screen", "To unsubscribe from events or timers", "To reset state to zero", "To delete the component"], "To unsubscribe from events or timers", "Cleanup functions prevent memory leaks.", "useEffect", "Intermediate");
  add("Which Hook caches a function definition between renders?", ["useMemo", "useCallback", "useRef", "useEffect"], "useCallback", "useCallback returns a memoized callback.", "useCallback", "Intermediate");
  add("Which Hook caches a calculated value between renders?", ["useMemo", "useCallback", "useRef", "useEffect"], "useMemo", "useMemo returns a memoized value.", "useMemo", "Intermediate");
  add("What happens when state changes in a React component?", ["The page reloads", "Only that component and its children re-render", "The whole app re-renders", "Nothing happens"], "Only that component and its children re-render", "React optimally re-renders the affected component tree.", "Components", "Intermediate");
  add("In an event handler, how do you prevent the default form submission behavior?", ["event.stop()", "event.preventDefault()", "return false", "event.cancel()"], "event.preventDefault()", "preventDefault() stops default browser actions.", "Form Submit", "Intermediate");
  add("If a <textarea> has value={text} and no onChange handler, what happens?", ["It behaves normally", "It is read-only", "It throws an error", "It updates automatically"], "It is read-only", "Without an onChange handler, a controlled input is read-only.", "Textarea", "Intermediate");
  add("How does React handle select elements?", ["The selected attribute is placed on the <option>", "The value attribute is placed on the root <select> tag", "It uses standard HTML", "It uses a special <ReactSelect> tag"], "The value attribute is placed on the root <select> tag", "React simplifies select tags by placing value on the parent.", "Select", "Intermediate");
  add("How can you pass a function from a parent component to a child component?", ["Through state", "Through props", "Using context only", "It is not possible"], "Through props", "Functions can be passed via props just like data.", "React Props", "Intermediate");
  add("What is 'prop drilling'?", ["Passing props directly to the child", "Passing props down multiple levels of components", "Extracting props from a child", "Deleting props"], "Passing props down multiple levels of components", "Prop drilling happens when props are passed through many layers.", "useContext", "Intermediate");
  add("How does useContext solve prop drilling?", ["It deletes props", "It provides data globally to all components in the tree", "It converts props to state", "It uses Redux"], "It provides data globally to all components in the tree", "Context makes data available anywhere in the tree.", "useContext", "Intermediate");
  add("When should you use useRef instead of useState?", ["When you want the component to re-render", "When you want to store a value that doesn't cause re-renders", "When you need to fetch data", "When you are handling forms"], "When you want to store a value that doesn't cause re-renders", "useRef does not trigger a re-render when its value changes.", "useRef", "Intermediate");
  add("What is a Custom Hook?", ["A built-in React feature", "A JavaScript function whose name starts with 'use' and calls other Hooks", "A component that returns JSX", "A Redux term"], "A JavaScript function whose name starts with 'use' and calls other Hooks", "Custom hooks extract logic for reuse.", "Custom Hooks", "Intermediate");
  add("In React Router v6, how do you define a route?", ["<Route path='/' element={<Home />} />", "<Route path='/'><Home /></Route>", "<Route path='/' component={Home} />", "<Router path='/home' />"], "<Route path='/' element={<Home />} />", "React Router v6 uses the element prop.", "React Router", "Intermediate");
  add("What does React.Suspense do?", ["Suspends the user session", "Displays a fallback UI while a component is loading asynchronously", "Stops errors from crashing the app", "Pauses the rendering indefinitely"], "Displays a fallback UI while a component is loading asynchronously", "Suspense is used for lazy loading components.", "React Suspense", "Intermediate");
  add("How do you implement CSS Modules in React?", ["Import style from './style.css'", "Import styles from './style.module.css'", "Use inline styles", "Use styled-components"], "Import styles from './style.module.css'", "CSS Modules require the .module.css extension.", "React CSS Modules", "Intermediate");
  add("Which array method is commonly used with the spread operator to add a new item?", ["arr.push(item)", "[item, ...arr]", "arr.concat(item)", "arr.unshift(item)"], "[item, ...arr]", "Spread creates a new array without mutating the original.", "ES6 Spread Operator", "Intermediate");
  add("What is Destructuring in function parameters?", ["function App({ name, age })", "function App(props.name)", "function App(...props)", "function App(props[0])"], "function App({ name, age })", "You can destructure props directly in the signature.", "Props Destructuring", "Intermediate");
  add("If a component receives props.children, what does it represent?", ["The child components defined inside the component's opening and closing tags", "An array of sibling components", "The parent's state", "A function"], "The child components defined inside the component's opening and closing tags", "children represents nested elements.", "Props Children", "Intermediate");
  add("How do you conditionally render a component using the logical && operator?", ["condition && <Component />", "condition ? <Component />", "if (condition) <Component />", "<Component if={condition} />"], "condition && <Component />", "The && operator is used for short-circuit rendering.", "React Conditionals", "Intermediate");
  add("If condition is false, what does `condition && <Component />` render?", ["null", "false", "<Component />", "An error"], "false", "React ignores false and renders nothing.", "React Conditionals", "Intermediate");
  add("What is the main difference between functional and class components?", ["Classes can use Hooks", "Functions don't have lifecycle methods (but use Hooks instead)", "Functions are faster", "Functions can't receive props"], "Functions don't have lifecycle methods (but use Hooks instead)", "Functions use Hooks for state and lifecycles.", "Function Components", "Intermediate");
  add("Can a component's state be accessed by its parent?", ["Yes, directly", "No, state is local to the component unless lifted up", "Yes, using refs", "Yes, using props"], "No, state is local to the component unless lifted up", "State is isolated inside its component.", "Components", "Intermediate");
  add("What does the 'dispatch' function do in useReducer?", ["Updates state directly", "Triggers an action to be handled by the reducer", "Fetches data from an API", "Clears the state"], "Triggers an action to be handled by the reducer", "dispatch sends an action to the reducer.", "useReducer", "Intermediate");
  add("In useReducer, what does the reducer function return?", ["The previous state", "The new state", "A JSX element", "An action object"], "The new state", "The reducer calculates and returns the updated state.", "useReducer", "Intermediate");
  add("What does React.memo do?", ["Memoizes a function", "Memoizes a component to prevent unnecessary re-renders", "Creates a Ref", "Acts as Context"], "Memoizes a component to prevent unnecessary re-renders", "React.memo skips re-rendering if props don't change.", "React.memo", "Intermediate");
  add("If you pass an inline object as a prop to a React.memo component, what happens?", ["It breaks the component", "It always re-renders because a new object is created every render", "It improves performance", "It behaves normally"], "It always re-renders because a new object is created every render", "Inline objects fail shallow equality checks.", "React.memo", "Intermediate");
  add("What does the dependency array in useCallback do?", ["Recreates the function when dependencies change", "Recreates the function on every render", "Stops the component from rendering", "Updates the state"], "Recreates the function when dependencies change", "The function is only recreated if a dependency changes.", "useCallback", "Intermediate");
  add("What happens if you mutate state directly like `this.state.name = 'John'`?", ["React updates the DOM", "React does not re-render the component", "React throws an error", "The app crashes"], "React does not re-render the component", "Direct mutation doesn't trigger a re-render.", "Components", "Intermediate");
  add("How does React Portals work?", ["They move state globally", "They render children into a DOM node outside the parent hierarchy", "They fetch data", "They handle routing"], "They render children into a DOM node outside the parent hierarchy", "Portals are used for modals and tooltips.", "React Portals", "Intermediate");
  add("What is the use of forwardRef?", ["To pass a ref to a child component", "To move backward in routing", "To update state", "To define a global variable"], "To pass a ref to a child component", "forwardRef allows parent components to access child DOM nodes.", "React Forward Ref", "Intermediate");
  add("What is the purpose of the Sass preprocessor in React?", ["To write HTML", "To manage state", "To use variables and nested rules in CSS", "To perform HTTP requests"], "To use variables and nested rules in CSS", "Sass allows advanced CSS authoring.", "React Sass", "Intermediate");

  // --- 25 SLIGHTLY DIFFICULT / DEBUGGING QUESTIONS ---
  add("What is wrong with this code? `const [count, setCount] = useState(0); setCount(count++);`", ["You cannot use const with useState", "count++ mutates the state directly", "setCount requires an object", "useState should be imported as default"], "count++ mutates the state directly", "count++ modifies the variable before passing it.", "useState", "Slightly Difficult");
  add("What is wrong with this code? `useEffect(() => { setInterval(() => console.log('Hi'), 1000) })`", ["setInterval cannot be used in React", "It runs on every render and creates multiple intervals", "The arrow function syntax is wrong", "useEffect must return a string"], "It runs on every render and creates multiple intervals", "Missing dependency array causes repeated interval creation.", "useEffect", "Slightly Difficult");
  add("Why will this cause an infinite loop? `useEffect(() => { setCount(count + 1); }, [count]);`", ["useEffect cannot update state", "Updating count triggers useEffect, which updates count again", "The dependency array syntax is wrong", "count must be a string"], "Updating count triggers useEffect, which updates count again", "The dependency triggers a re-render which triggers the effect continuously.", "useEffect", "Slightly Difficult");
  add("What is wrong with this list? `<ul>{items.map(item => <li>{item.name}</li>)}</ul>`", ["Missing map keyword", "Missing return keyword", "Missing a unique key prop on the <li>", "Should use a for loop"], "Missing a unique key prop on the <li>", "Lists require a key prop for each element.", "Keys", "Slightly Difficult");
  add("What happens here? `const value = useRef(0); value.current = value.current + 1;`", ["The component re-renders", "The value updates but the component does NOT re-render", "React throws an error", "The value remains 0"], "The value updates but the component does NOT re-render", "Updating a ref does not trigger a re-render.", "useRef", "Slightly Difficult");
  add("What is wrong with this code? `if(condition) { const [val, setVal] = useState(0); }`", ["useState cannot take 0", "Hooks cannot be called conditionally", "setVal is misspelled", "condition must be boolean"], "Hooks cannot be called conditionally", "Hooks must be called at the top level.", "What is Hooks?", "Slightly Difficult");
  add("What is the output of `console.log(count)` right after `setCount(count + 1)` in a function?", ["The updated count", "The old count", "undefined", "null"], "The old count", "State updates are asynchronous.", "useState", "Slightly Difficult");
  add("How do you fix this form? `<input type=\"text\" value={name} />` (It is read-only)", ["Add an id", "Add an onChange handler to update state", "Change type to string", "Use defaultValue instead"], "Add an onChange handler to update state", "Controlled components need an onChange handler.", "React Forms", "Slightly Difficult");
  add("What is wrong with this import? `import React, { useState } from 'React';`", ["useState is not exported from React", "The package name 'React' should be lowercase 'react'", "React must be destructured", "Nothing is wrong"], "The package name 'React' should be lowercase 'react'", "Package names are case-sensitive.", "React Introduction", "Slightly Difficult");
  add("What is wrong with this component? `function myComponent() { return <div>Hi</div>; }`", ["Component names must start with a capital letter", "div must be closed", "function must be capitalized", "Nothing"], "Component names must start with a capital letter", "React treats lowercase names as standard HTML tags.", "Function Components", "Slightly Difficult");
  add("What is wrong here? `return ( <h1>Hello</h1> <h2>World</h2> )`", ["Missing parentheses", "Multiple root elements without a parent", "Missing return keyword", "Variables cannot be returned"], "Multiple root elements without a parent", "JSX must have a single root element.", "JSX Intro", "Slightly Difficult");
  add("Identify the problem: `<button onclick={handleClick}>Click</button>`", ["onclick should be onClick", "handleClick must be invoked", "button is not valid in React", "Cannot use braces"], "onclick should be onClick", "React uses camelCase for events.", "React Events", "Slightly Difficult");
  add("Identify the problem: `<img src='image.png'>`", ["img is not supported", "Missing alt text", "Missing self-closing slash `/>`", "src must be a URL"], "Missing self-closing slash `/>`", "JSX tags must always be closed.", "JSX Intro", "Slightly Difficult");
  add("What happens if you use `class` instead of `className` in JSX?", ["The app crashes immediately", "It works but logs a warning in the console", "The class is ignored", "React converts it automatically without warnings"], "It works but logs a warning in the console", "className is the proper syntax in React.", "JSX Attributes", "Slightly Difficult");
  add("What is wrong with `style={color: red}`?", ["Missing double curly braces `{{ }}`", "color must be uppercase", "red must be a number", "style cannot be used"], "Missing double curly braces `{{ }}`", "Inline styles require an object inside the JSX expression.", "React CSS Styling", "Slightly Difficult");
  add("Identify the error: `const App = () => { return <div> {if(true){'Yes'}} </div>; }`", ["Cannot use `if` statements inside JSX expressions", "Missing else statement", "Cannot return strings", "Div must be a span"], "Cannot use `if` statements inside JSX expressions", "Use ternary operators instead of `if` inside JSX.", "JSX If Statements", "Slightly Difficult");
  add("Why is `useContext(MyContext)` returning undefined?", ["The component is not wrapped in a Context Provider", "useContext is misspelled", "Context only works in classes", "MyContext must be a string"], "The component is not wrapped in a Context Provider", "Context requires a Provider higher in the tree.", "useContext", "Slightly Difficult");
  add("What is wrong with `const obj = { name: 'A' }; return <div>{obj}</div>`?", ["Objects are not valid as a React child", "Missing return statement", "obj is constant", "Div must have a class"], "Objects are not valid as a React child", "React cannot render JS objects directly.", "JSX Expressions", "Slightly Difficult");
  add("What does this code do? `const copy = [...items];`", ["Modifies the items array", "Creates a shallow copy of the items array", "Sorts the array", "Converts array to string"], "Creates a shallow copy of the items array", "Spread creates a shallow clone.", "ES6 Spread Operator", "Slightly Difficult");
  add("Why might `useCallback` be causing performance issues?", ["It cannot be used with React.memo", "The dependency array is missing, causing it to recreate on every render", "It fetches data repeatedly", "It clears state"], "The dependency array is missing, causing it to recreate on every render", "Without dependencies, it does not memoize properly.", "useCallback", "Slightly Difficult");
  add("Identify the problem: `props.name = 'John';` inside a child component.", ["Props are read-only and cannot be mutated", "name must be an object", "props must be destructured", "You need to use `this.props`"], "Props are read-only and cannot be mutated", "Props must not be modified by the receiving component.", "React Props", "Slightly Difficult");
  add("What is wrong with `const { name, age } = user[0];` if user is `{name: 'A', age: 1}`?", ["user is an object, not an array", "Variables cannot be destructured", "Syntax error", "It is correct"], "user is an object, not an array", "You cannot use array index `[0]` on an object.", "ES6 Destructuring", "Slightly Difficult");
  add("Identify the issue: `<Route path='/' element={Home} />` in React Router v6.", ["element prop requires JSX, like `<Home />`", "path is missing", "Route must be lowercase", "element should be component"], "element prop requires JSX, like `<Home />`", "React Router v6 needs an element, not a reference.", "React Router", "Slightly Difficult");
  add("Why might a controlled checkbox not toggle?", ["It lacks a checked prop or onChange handler", "Checkboxes aren't supported", "Value must be a string", "It must be wrapped in a form"], "It lacks a checked prop or onChange handler", "Controlled checkboxes need a checked prop and onChange.", "Checkbox", "Slightly Difficult");
  add("What is the correct way to handle multiple input fields with one state object?", ["Update all fields individually", "Use `[event.target.name]: event.target.value`", "Use refs for each", "Use Redux"], "Use `[event.target.name]: event.target.value`", "Dynamic keys allow handling multiple fields efficiently.", "Multiple Inputs", "Slightly Difficult");

  return q;
};

const content = "export const initialQuestions = " + JSON.stringify(generateQuestions(), null, 2) + ";\n";
fs.writeFileSync('./src/data/questions.js', content);
console.log('100 Questions generated successfully!');
